services:
  - type: web
    name: memorial-candle
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 4 --timeout 120 app:app
    healthCheckPath: /health

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: ADMIN_PASSWORD
        sync: false

      - key: DATABASE_PATH
        value: /var/data/memorial.db

      - key: MEMORIAL_NAME
        sync: false

      - key: MEMORIAL_MESSAGE
        sync: false

      - key: BURIAL_DATE
        sync: false

      - key: BURIAL_VENUE
        sync: false

      - key: BURIAL_DATETIME
        value: "2026-08-19T10:00:00+03:00"

      - key: BURIAL_MAP_URL
        value: "https://www.google.com/maps/search/?api=1&query=Miyuga%2C%20Homa%20Bay%20County%2C%20Kenya"

      - key: PHOTO_URL
        value: /static/mum.jpg

      - key: EULOGY_FILENAME
        value: eulogy.pdf

      - key: MPESA_NUMBER
        sync: false

      - key: MPESA_NAME
        sync: false

      - key: CONTRIBUTION_PURPOSE
        sync: false

      - key: ORGANIZER_PHONE
        sync: false

      - key: WHATSAPP_GROUP_NAME
        value: Family Burial Contribution Group

      - key: WHATSAPP_GROUP_URL
        value: "https://chat.whatsapp.com/Ld8zx7Bey5w5QdR2jOP3bn"

      - key: FAMILY_UPDATE
        value: "Join the official WhatsApp group for contribution updates, transport coordination and family announcements."

      - key: LIVESTREAM_URL
        value: "https://www.youtube.com/watch?v=MzxQsNAAjdw"

      - key: VIDEO_MEMORIES
        value: "https://www.youtube.com/watch?v=r_3_HGehp30&t=1482s,https://youtu.be/fA0kE9eZKNQ"

    disk:
      name: memorial-data
      mountPath: /var/data
      sizeGB: 1
